//
//  IrregularVerbs.swift
//  LearningVerbs App
//
//  Created by Melkor on 12/15/23.
//

import UIKit

final class IrregularVerbs {
    
    // Singleton
    static var shared = IrregularVerbs()
    private init() {
        configureVerbs()
    }
    
    // MARK: - Properties
    private(set) var verbs: [Verb] = []
    var selectedVerbs: [Verb] = []
    
    // MARK: - Methods
    private func configureVerbs() {
        verbs = [
                Verb(infinitive: "abide", pastSimple: "abode", participle: "abode"),
                Verb(infinitive: "arise", pastSimple: "arose", participle: "arisen"),
                Verb(infinitive: "awaken", pastSimple: "awoke", participle: "awoken"),
                Verb(infinitive: "be", pastSimple: "was/were", participle: "been"),
                Verb(infinitive: "bear", pastSimple: "bore", participle: "borne"),
                Verb(infinitive: "beat", pastSimple: "beat", participle: "beaten"),
                Verb(infinitive: "become", pastSimple: "became", participle: "become"),
                Verb(infinitive: "begin", pastSimple: "began", participle: "begun"),
                Verb(infinitive: "behold", pastSimple: "beheld", participle: "beheld"),
                Verb(infinitive: "bend", pastSimple: "bent", participle: "bent"),
                Verb(infinitive: "bet", pastSimple: "bet", participle: "bet"),
                Verb(infinitive: "bid", pastSimple: "bade", participle: "bidden"),
                Verb(infinitive: "bind", pastSimple: "bound", participle: "bound"),
                Verb(infinitive: "bite", pastSimple: "bit", participle: "bitten"),
                Verb(infinitive: "bleed", pastSimple: "bled", participle: "bled"),
                Verb(infinitive: "blow", pastSimple: "blew", participle: "blown"),
                Verb(infinitive: "break", pastSimple: "broke", participle: "broken"),
                Verb(infinitive: "breed", pastSimple: "bred", participle: "bred"),
                Verb(infinitive: "bring", pastSimple: "brought", participle: "brought"),
                Verb(infinitive: "broadcast", pastSimple: "broadcast", participle: "broadcast"),
                Verb(infinitive: "build", pastSimple: "built", participle: "built"),
                Verb(infinitive: "burn", pastSimple: "burnt/burned", participle: "burnt/burned"),
                Verb(infinitive: "burst", pastSimple: "burst", participle: "burst"),
                Verb(infinitive: "buy", pastSimple: "bought", participle: "bought"),
                Verb(infinitive: "can", pastSimple: "could", participle: "could"),
                Verb(infinitive: "catch", pastSimple: "caught", participle: "caught"),
                Verb(infinitive: "choose", pastSimple: "chose", participle: "chosen"),
                Verb(infinitive: "come", pastSimple: "came", participle: "come"),
                Verb(infinitive: "cost", pastSimple: "cost", participle: "cost"),
                Verb(infinitive: "cut", pastSimple: "cut", participle: "cut"),
                Verb(infinitive: "deal", pastSimple: "dealt", participle: "dealt"),
                Verb(infinitive: "decide", pastSimple: "decided", participle: "decided"),
                Verb(infinitive: "do", pastSimple: "did", participle: "done"),
                Verb(infinitive: "draw", pastSimple: "drew", participle: "drawn"),
                Verb(infinitive: "dream", pastSimple: "dreamt/dreamed", participle: "dreamt/dreamed"),
                Verb(infinitive: "drink", pastSimple: "drank", participle: "drunk"),
                Verb(infinitive: "drive", pastSimple: "drove", participle: "driven"),
                Verb(infinitive: "eat", pastSimple: "ate", participle: "eaten"),
                Verb(infinitive: "fall", pastSimple: "fell", participle: "fallen"),
                Verb(infinitive: "feed", pastSimple: "fed", participle: "fed"),
                Verb(infinitive: "feel", pastSimple: "felt", participle: "felt"),
                Verb(infinitive: "fight", pastSimple: "fought", participle: "fought"),
                Verb(infinitive: "find", pastSimple: "found", participle: "found"),
                Verb(infinitive: "fit", pastSimple: "fit/fitted", participle: "fit/fitted"),
                Verb(infinitive: "fly", pastSimple: "flew", participle: "flown"),
                Verb(infinitive: "forget", pastSimple: "forgot", participle: "forgotten"),
                Verb(infinitive: "forgive", pastSimple: "forgave", participle: "forgiven"),
                Verb(infinitive: "freeze", pastSimple: "froze", participle: "frozen"),
                Verb(infinitive: "get", pastSimple: "got", participle: "got/gotten"),
                Verb(infinitive: "give", pastSimple: "gave", participle: "given"),
                Verb(infinitive: "go", pastSimple: "went", participle: "gone"),
                Verb(infinitive: "grow", pastSimple: "grew", participle: "grown"),
                Verb(infinitive: "hang", pastSimple: "hung", participle: "hung"),
                Verb(infinitive: "have", pastSimple: "had", participle: "had"),
                Verb(infinitive: "hear", pastSimple: "heard", participle: "heard"),
                Verb(infinitive: "hide", pastSimple: "hid", participle: "hidden"),
                Verb(infinitive: "hit", pastSimple: "hit", participle: "hit"),
                Verb(infinitive: "hold", pastSimple: "held", participle: "held"),
                Verb(infinitive: "hurt", pastSimple: "hurt", participle: "hurt"),
                Verb(infinitive: "keep", pastSimple: "kept", participle: "kept"),
                Verb(infinitive: "know", pastSimple: "knew", participle: "known"),
                Verb(infinitive: "lay", pastSimple: "laid", participle: "laid"),
                Verb(infinitive: "lead", pastSimple: "led", participle: "led"),
                Verb(infinitive: "learn", pastSimple: "learnt/learned", participle: "learnt/learned"),
                Verb(infinitive: "leave", pastSimple: "left", participle: "left"),
                Verb(infinitive: "make", pastSimple: "made", participle: "made"),
                Verb(infinitive: "mean", pastSimple: "meant", participle: "meant"),
                Verb(infinitive: "meet", pastSimple: "met", participle: "met"),
                Verb(infinitive: "mistake", pastSimple: "mistook", participle: "mistaken"),
                Verb(infinitive: "mow", pastSimple: "mowed", participle: "mowed"),
                Verb(infinitive: "must", pastSimple: "must", participle: "must"),
                Verb(infinitive: "need", pastSimple: "needed", participle: "needed"),
                Verb(infinitive: "put", pastSimple: "put", participle: "put"),
                Verb(infinitive: "read", pastSimple: "read", participle: "read"),
                Verb(infinitive: "ride", pastSimple: "rode", participle: "ridden"),
                Verb(infinitive: "ring", pastSimple: "rang", participle: "rung"),
                Verb(infinitive: "rise", pastSimple: "rose", participle: "risen"),
                Verb(infinitive: "run", pastSimple: "ran", participle: "run"),
                Verb(infinitive: "say", pastSimple: "said", participle: "said"),
                Verb(infinitive: "see", pastSimple: "saw", participle: "seen"),
                Verb(infinitive: "seek", pastSimple: "sought", participle: "sought"),
                Verb(infinitive: "sell", pastSimple: "sold", participle: "sold"),
                Verb(infinitive: "send", pastSimple: "sent", participle: "sent"),
                Verb(infinitive: "set", pastSimple: "set", participle: "set"),
                Verb(infinitive: "shake", pastSimple: "shook", participle: "shaken"),
                Verb(infinitive: "shall", pastSimple: "shall", participle: "shall"),
                Verb(infinitive: "shear", pastSimple: "sheared", participle: "sheared"),
                Verb(infinitive: "shine", pastSimple: "shone", participle: "shone"),
                Verb(infinitive: "shoot", pastSimple: "shot", participle: "shot"),
                Verb(infinitive: "show", pastSimple: "showed", participle: "shown"),
                Verb(infinitive: "shut", pastSimple: "shut", participle: "shut"),
                Verb(infinitive: "sink", pastSimple: "sank", participle: "sunk"),
                Verb(infinitive: "sit", pastSimple: "sat", participle: "sat"),
                Verb(infinitive: "speak", pastSimple: "spoke", participle: "spoken"),
                Verb(infinitive: "spend", pastSimple: "spent", participle: "spent"),
                Verb(infinitive: "spell", pastSimple: "spelt/spelled", participle: "spelt/spelled"),
                Verb(infinitive: "split", pastSimple: "split", participle: "split"),
                Verb(infinitive: "spoil", pastSimple: "spoilt/spoiled", participle: "spoilt/spoiled"),
                Verb(infinitive: "spread", pastSimple: "spread", participle: "spread"),
                Verb(infinitive: "spring", pastSimple: "sprang", participle: "sprung"),
                Verb(infinitive: "stand", pastSimple: "stood", participle: "stood"),
                Verb(infinitive: "steal", pastSimple: "stole", participle: "stolen"),
                Verb(infinitive: "stick", pastSimple: "stuck", participle: "stuck"),
                Verb(infinitive: "sting", pastSimple: "stung", participle: "stung"),
                Verb(infinitive: "stink", pastSimple: "stank", participle: "stunk"),
                Verb(infinitive: "strike", pastSimple: "struck", participle: "struck"),
                Verb(infinitive: "strive", pastSimple: "strove", participle: "striven"),
                Verb(infinitive: "take", pastSimple: "took", participle: "taken"),
                Verb(infinitive: "teach", pastSimple: "taught", participle: "taught"),
                Verb(infinitive: "tear", pastSimple: "tore", participle: "torn"),
                Verb(infinitive: "tell", pastSimple: "told", participle: "told"),
                Verb(infinitive: "think", pastSimple: "thought", participle: "thought"),
                Verb(infinitive: "throw", pastSimple: "threw", participle: "thrown"),
                Verb(infinitive: "understand", pastSimple: "understood", participle: "understood"),
                Verb(infinitive: "wake", pastSimple: "woke", participle: "woken"),
                Verb(infinitive: "wear", pastSimple: "wore", participle: "worn"),
                Verb(infinitive: "win", pastSimple: "won", participle: "won"),
                Verb(infinitive: "write", pastSimple: "wrote", participle: "written"),
                Verb(infinitive: "wind", pastSimple: "wound", participle: "wound")
        ]
    }
}
